apiVersion: apps/v1
kind: Deployment
metadata:
  name: production
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: production
spec:
  selector:
    app: nginx
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
  type: LoadBalancer
